name: Generate Trophy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Testar GITHUB_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Testando acesso ao repositório..."

          curl -f \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ThiaggoSylva/ThiaggoSylva

          echo "Token conseguiu acessar o repositório."

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        env:
          GITHUB_TOKEN1: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN2: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: ThiaggoSylva
          token: ${{ secrets.GITHUB_TOKEN }}
          file: ./trophy.svg
          theme: default
          max-cols: 6
          max-rows: 2
          panel-size: 115
          margin-width: 10
          margin-height: 10

      - name: Verify trophy
        run: |
          if [ ! -s trophy.svg ]; then
            echo "ERRO: trophy.svg não foi gerado."
            exit 1
          fi

          echo "trophy.svg gerado:"
          ls -lh trophy.svg

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add trophy.svg

          if git diff --cached --quiet; then
          echo "Nenhuma alteração no trophy.svg"
          exit 0
          fi

          git commit -m "chore: update GitHub trophy"
          git push